### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by dcy0577** [isse-augsburg/ecml22-grape#1]
Hi thanks for your amazing work. Where can I find the requirements.txt to install the dependencies?

**Comment by Groot21** [comment]
Dear @dcy0577, 

Thank you for your kind words and your interest in using our code repository! We apologize for the inconvenience caused by the absence of the requirements.txt file. We have now added it to the repository and you should be able to find it in the root directory. Please let us know if you have any further questions or issues.

Thank you again for your support and we hope our code proves helpful to you.
